name: tirtik_app
description: Flutter Base Project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  path: ^1.8.0
  web_socket_channel: ^2.2.0
  http: ^0.13.5
  get: ^4.6.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter:
  uses-material-design: true

  # assets:
    # - assets/animation/
    # - assets/images/flags/
    # - assets/images/logo/
    # - assets/images/icons/
    # - assets/images/icons/bottom_navigation/

  # fonts:
  #   - family: Barlow
  #     fonts:
  #       - asset: assets/fonts/Barlow-Light.ttf
  #         weight: 300
  #       - asset: assets/fonts/Barlow-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Barlow-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Barlow-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Barlow-Bold.ttf
  #         weight: 700


